
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MARIAM NASSER SAYED
 */
public class AdminDoctors extends javax.swing.JFrame {

   Connection conn=null;
    PreparedStatement ps;
    java.sql.Statement st;
    ResultSet rs;
                private void clear()
    {
        pname.setText("");
        hname.setText("");
        dname.setText("");
        ID.setText("");
      
                }

         public void loadcombo1()
    {
        // TO SHOW DATA FROM DB IN COMBOBOX
        
         try {
              Class.forName("com.mysql.jdbc.Driver");
              Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare","root","");
              PreparedStatement ps =(PreparedStatement) con.prepareStatement( "select id from appointements");
              rs=ps.executeQuery();
              while(rs.next())
              {
                idcombo.addItem(rs.getString("id"));
                idcombo.setSelectedItem("");

              }
          } 
          catch (Exception ex) 
          {
              Logger.getLogger(AdminDoctors.class.getName()).log(Level.SEVERE, null, ex);
          }
    }
    public AdminDoctors() {
        initComponents();
        loadcombo1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        apptable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        idcombo = new javax.swing.JComboBox<>();
        ID = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        hname = new javax.swing.JTextField();
        dname = new javax.swing.JTextField();
        apptype = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "date", "appointment_type", "patient_name", "hosp_name", "doc_name"
            }
        ));
        jScrollPane1.setViewportView(apptable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 960, 310));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, 110, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 380, 110, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 450, 110, -1));

        Cancel.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 520, 110, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, 110, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 660, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Table ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Patient Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Hospital Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Appointement Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Doctotr Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 80, -1));

        date.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 250, 30));

        getContentPane().add(idcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 80, -1));
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 90, -1));
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 230, -1));
        getContentPane().add(hname, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 250, -1));
        getContentPane().add(dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 240, -1));
        getContentPane().add(apptype, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 230, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).jpg"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(1250, 850));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         AdminForm af=new AdminForm();
                af.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    String sql="SELECT * FROM appointements";
                
          try
            {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare","root","");
        PreparedStatement ps;
        ps = (PreparedStatement) con.prepareStatement(sql);
        ResultSet rs=ps.executeQuery(sql);
        DefaultTableModel mod= (DefaultTableModel) apptable.getModel();
        mod.setRowCount(0);
        while(rs.next())
        {
            mod.addRow(new String[] {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
        }
        
        

            }
            catch(Exception e)
            {
                
            }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                 if(ID.getText().isEmpty() || pname.getText().isEmpty() || hname.getText().isEmpty()||
                dname.getText().isEmpty() )
        {
           JOptionPane.showMessageDialog(this,"Missing Information");

        }
        else
        {   
           
            try
            {
                
            
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare","root","");  
        PreparedStatement ps =(PreparedStatement) con.prepareStatement( "insert into appointements (id,date,appointment_type,patient_name,hosp_name,doc_name) VALUES (?,?,?,?,?,?)");
        ps.setString(1, ID.getText());
        ps.setString(2, ((JTextField) date.getDateEditor().getUiComponent()).getText());
        ps.setString(3,apptype.getText());
        ps.setString(4,pname.getText());
        ps.setString(5,hname.getText());
        ps.setString(6,dname.getText());
        int row=ps.executeUpdate();
        JOptionPane.showMessageDialog(this,"Recored Added");
        con.close();
        clear();

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"In Catch");

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                //UPDATE BUTTON
        
        if(idcombo.getSelectedIndex()==-1|| pname.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Select Table Id and Patient Name Fields");
        } 
        else
        {
 
             try
            {
       Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare","root","");
       PreparedStatement ps =(PreparedStatement) con.prepareStatement( "update appointements set  date=? where id= "+idcombo.getSelectedItem() );
    
        ps.setString(1, ((JTextField) date.getDateEditor().getUiComponent()).getText());
     
       
        int row=ps.executeUpdate();
        JOptionPane.showMessageDialog(this,"Recorde Updated");
        con.close();
        clear();
            }
        catch(Exception e)
        {
            
        }
          
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        // CANCEL  BUTTON
              if(idcombo.getSelectedIndex()==-1|| pname.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Select Table Id and Patient Name Fields ");
        } 
       // NOTE : ONLY DELETE RECERDE NO FORIEGN KEY IN OTHER TABLE
         else
        {
         try {
             Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare","root","");
            String query="delete from appointements where id= "+idcombo.getSelectedItem();
            Statement del=(Statement) con.createStatement();
            del.executeUpdate(query);
              
              JOptionPane.showMessageDialog(this,"Appointement Canceled");

      
          } 
          catch (Exception ex) 
          {
              Logger.getLogger(AdminDoctors.class.getName()).log(Level.SEVERE, null, ex);
          }
        }

    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDoctors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField ID;
    private javax.swing.JTable apptable;
    private javax.swing.JTextField apptype;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField dname;
    private javax.swing.JTextField hname;
    private javax.swing.JComboBox<String> idcombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pname;
    // End of variables declaration//GEN-END:variables
}
