
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MARIAM NASSER SAYED
 */
public class AdminMedicin extends javax.swing.JFrame {

       Connection conn=null;
    PreparedStatement ps;
    Statement st;
    ResultSet rs;
      private void clear() {

        arname.setText("");
        enname.setText("");
        medcode.setText("");
        price.setText("");

    }

    public void loadcombo() {
        // TO SHOW DATA FROM DB IN COMBOBOX

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare", "root", "");
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("select MEDCODE from pharmacy");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                medcod.addItem(rs.getString("MEDCODE"));
                medcod.setSelectedItem("");

            }
        } catch (Exception ex) {
            Logger.getLogger(AdminMedicin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public AdminMedicin() {
        initComponents();
        loadcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        medcode = new javax.swing.JTextField();
        enname = new javax.swing.JTextField();
        arname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        medcod = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MEDCODE", "ARMEDNAME", "ENGMEDNAME", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(medtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 970, 410));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Medicin Code");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Arabic Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 130, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("English Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 140, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 60, -1));

        medcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medcodeActionPerformed(evt);
            }
        });
        getContentPane().add(medcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 90, -1));
        getContentPane().add(enname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 250, -1));

        arname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arnameActionPerformed(evt);
            }
        });
        getContentPane().add(arname, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 250, -1));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 190, -1));

        getContentPane().add(medcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 100, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 620, 110, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 560, 110, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 500, 110, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 440, 110, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 370, 110, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setText("View");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 300, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download (1).jpg"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(1850, 850));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -240, -1, 1230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medcodeActionPerformed

    private void arnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          AdminForm af=new AdminForm();
                af.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                ///VIEW BUTTON

        String sql = "SELECT * FROM `pharmacy`";

        try {
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare", "root", "");
            PreparedStatement ps;
            ps = (PreparedStatement) con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery(sql);
            DefaultTableModel mod = (DefaultTableModel) medtable.getModel();
            mod.setRowCount(0);
            while (rs.next()) {
                mod.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }

        } catch (Exception e) {

        }


        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //UPDATE BUTTON

        if (medcod.getSelectedIndex() == -1 ||enname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select Medicin Name and Engkish name Fields");
        } else {

            try {
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare", "root", "");
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("update pharmacy set PRICE=? where MEDCODE= " + medcod.getSelectedItem());

                ps.setString(1, price.getText());
               
                int row = ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Recorde Updated");
                con.close();
                clear();
            } catch (Exception e) {

            }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           // DELETE BUTTON
        if (medcod.getSelectedIndex() == -1 || enname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select Medicin Code and Price Fields ");
        } // NOTE : ONLY DELETE RECERDE NO FORIEGN KEY IN OTHER TABLE
        else {
            try {
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare", "root", "");
                String query = "delete from pharmacy where MEDCODE= " + medcod.getSelectedItem();
                Statement del = (Statement) con.createStatement();
                del.executeUpdate(query);

                JOptionPane.showMessageDialog(this, "Recorde Deleted");

            } catch (Exception ex) {
                Logger.getLogger(AdminMedicin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                // ADD BUTTON
        if (medcode.getText().isEmpty() || arname.getText().isEmpty() || enname.getText().isEmpty() || price.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information");

        } else {
            // JOptionPane.showMessageDialog(this,"else");
            try {
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/midcare", "root", "");
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into pharmacy (MEDCODE,ENGMEDNAME,ARMEDNAME,PRICE) VALUES (?,?,?,?)");
                ps.setString(1, medcode.getText());
                ps.setString(2, enname.getText());
                ps.setString(3, arname.getText());
                ps.setString(4, price.getText());
                int row = ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Recored Added");
                con.close();
                clear();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "In Catch");

            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMedicin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMedicin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMedicin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMedicin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMedicin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arname;
    private javax.swing.JTextField enname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> medcod;
    private javax.swing.JTextField medcode;
    private javax.swing.JTable medtable;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
