
import javax.swing.JOptionPane;

public class SplashForm extends javax.swing.JFrame {

    
    public SplashForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        loading = new javax.swing.JLabel();
        loadingvalue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue-background.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1250, 850));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -70, 2350, 810));
        getContentPane().add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 764, 1330, 30));

        loading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loading.setText("Loading ....");
        getContentPane().add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, -1, -1));

        loadingvalue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loadingvalue.setText("0 %");
        getContentPane().add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 740, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SplashForm sp = new SplashForm();
        sp.setVisible(true);
        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(50);
                sp.loadingvalue.setText(i + "%");

                if (i == 10) {
                    sp.loading.setText("Turning On Modules...");
                }
                if (i == 20) {
                    sp.loading.setText("Loading Modules...");
                }
                if (i == 50) {
                    sp.loading.setText("Connecting To DataBase...");
                }
                if (i == 70) {
                    sp.loading.setText("Connecting To Successful...");
                }
                if (i == 80) {
                    sp.loading.setText("Launching Application...");
                }
                sp.loadingbar.setValue(i);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        new LoginForm().setVisible(true);
        sp.dispose();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashForm().setVisible(false);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loading;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadingvalue;
    // End of variables declaration//GEN-END:variables
}
